apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app
    # This label is often used by Prometheus to discover services
    release: prometheus 
spec:
  type: LoadBalancer
  selector:
    app: java-app
  ports:
  - name: web-metrics
    port: 80
    targetPort: 8080
